spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: H2
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        query.in_clause_parameter_padding: true
  datasource:
    url:
      jdbc:h2:mem:board
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
